text edit added
Worldival/sum_practise_2023 pull request #10
Opened 2023-07-03 20:26 UTC by HelpMySoul

2023-07-03 20:34 UTC, spanditime requested changes

2023-07-03 20:34 UTC, spanditime commented on sum_practise_2023/sum_practise_2023/Document.cs
#157 На строчку выше есть ивент, который вызывается во всех случаях когда необходимо редактирование, зачем ещё один хэндлер ивентов мыши полностью повторяющиеся внутренний?

2023-07-03 20:34 UTC, spanditime commented on sum_practise_2023/sum_practise_2023/Document.cs
>          {
Вот тут должно вызываться форма редактирования

2023-07-03 20:34 UTC, spanditime commented on sum_practise_2023/sum_practise_2023/Document.cs
> +            cp.comp.MouseDown += new MouseEventHandler(ShowEditForm);
Сверху ивент вызывающий при всех сценария в которых элемент должен быть отредактировал, твой обработчик копирует код из внутреннего хэндлера событий мыши, зачем)

2023-07-03 21:02 UTC, HelpMySoul commented
я прост думал TextFieldEditing чтот твое другое будет и не стал там срать, а так я не особо вникал, что ты писал, просто ищу места для присоединению к твоему, мне фиксить или сам справишься?

2023-07-04 08:39 UTC, spanditime commented
@HelpMySoul фикси, я залью

2023-07-04 18:47 UTC, merged